# Generated by Django 4.2.3 on 2023-08-02 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0002_alter_rent_fixed_price_alter_rent_per_km_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_from', models.DateTimeField()),
                ('booking_till', models.DateTimeField()),
                ('booked_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('booked', 'Booked'), ('cancelled_by_user', 'Cancelled by User'), ('cancelled_renter', 'Cancellled by Renter')], default='booked', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclecredentials')),
            ],
        ),
    ]
