# Generated by Django 4.2.3 on 2023-08-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('completed', 'completed'), ('cancelled_by_user', 'Cancelled by User'), ('cancelled_renter', 'Cancellled by Renter')], default='completed', max_length=30),
        ),
    ]
