# Generated by Django 4.2.3 on 2023-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_booking_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('booked', 'Booked'), ('available', 'Available'), ('cancelled_by_user', 'Cancelled by User'), ('cancelled_renter', 'Cancellled by Renter')], default='completed', max_length=30),
        ),
    ]
