# Generated by Django 4.2.3 on 2023-08-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled_user', 'Cancelled By User'), ('cancelled_renter', 'Cancelled by Renter')], default='booked', max_length=25),
        ),
    ]
