# Generated by Django 4.2.3 on 2023-07-26 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=9876541232, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$')], verbose_name='phone_number'),
            preserve_default=False,
        ),
    ]
