# Generated by Django 4.2.3 on 2023-08-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_dob_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_pro_pic.jpg', upload_to='profile_pics'),
        ),
    ]
