# Generated by Django 4.2.3 on 2023-08-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
