# Generated by Django 4.2.3 on 2023-08-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_driving_liscence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='customer',
        ),
    ]
