# Generated by Django 4.2.3 on 2023-08-01 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import vehicle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('renters', '0002_remove_renter_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('MPV', 'MPV')], max_length=20)),
                ('seating_capacity', models.PositiveIntegerField(default=2)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'CNG'), ('Hybrid(Petrol)', 'Hybrid(Petrol)'), ('Hybrid(Diesel)', 'Hybrid(Diesel)')], max_length=30)),
                ('ex_showroom_price', models.PositiveIntegerField(default=300000)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturing_year', models.PositiveIntegerField()),
                ('registration_number', models.CharField(max_length=14)),
                ('insurance', models.FileField(upload_to=vehicle.models.rename_insurance_file, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('rc_book_and_paper', models.FileField(upload_to=vehicle.models.rename_rc_book_and_paper, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('mileage_in_km', models.PositiveIntegerField()),
                ('features', models.CharField(max_length=150)),
                ('image1', models.ImageField(default='default_car_pic.jpg', upload_to=vehicle.models.rename_image_file)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Not_available', 'Not Available')], max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renters.renter')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_price', models.PositiveIntegerField()),
                ('per_km_rate', models.PositiveIntegerField()),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
