# Generated by Django 4.2.3 on 2023-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='fixed_price',
            field=models.PositiveIntegerField(default=2500),
        ),
        migrations.AlterField(
            model_name='rent',
            name='per_km_rate',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
