# Generated by Django 4.2.3 on 2023-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_rent_fixed_price_alter_rent_per_km_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecredentials',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('not_available', 'Not Available')], max_length=15),
        ),
    ]
