# Generated by Django 4.2.3 on 2023-08-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehiclecredentials_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecredentials',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('not_available', 'Not Available')], default='available', max_length=15),
        ),
    ]
