# Generated by Django 4.2.3 on 2023-08-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehiclecredentials_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecredentials',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('not_available', 'Not Available'), ('cancelled_by_user', 'Cancelled By User'), ('cancelled_by_renter', 'Cancelled by Renter')], default='available', max_length=25),
        ),
    ]
